CodeSystem: OSLABSpecimensCS
Id: oslab-specimens
Title: "OS LAB Microbiology Specimens CodeSystem"
Description: "The OS Lab Microbiology Specimens CodeSystem includes codes for specimens for use in a Laboratory Observation."
* ^meta.profile[+] = "http://hl7.org/fhir/StructureDefinition/shareablecodesystem"
* ^status = #draft
* ^extension[http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm].valueInteger = 0
* ^date = "2026-02-28"
* ^experimental = false
* ^caseSensitive = false
* #Swab "Swab" "Swab"
* #Tissue "Tissue specimen" "Tissue specimen"
* #LeftNeckTissue "Tissue specimen" "Tissue specimen"
* #Fluid "Fluid sample" "Fluid sample"
* #AsciticFluid "Ascitic fluid" "Ascitic fluid"
* #Mesh "Mesh" "Mesh"
* #Pus "Pus specimen" "Pus specimen"
* #Blood "Blood specimen" "Blood specimen"
* #Urine "Urine specimen" "Urine specimen"
* #Tip "Specimen from drain tip" "Specimen from drain tip"
* #Washing "Specimen obtained by lavage" "Specimen obtained by lavage"
* #Washings "Specimen obtained by lavage" "Specimen obtained by lavage"
* #Lavage "Specimen obtained by lavage" "Specimen obtained by lavage"
* #Bone "Specimen from bone" "Specimen from bone"
* #Aspirate "Specimen obtained by aspiration" "Specimen obtained by aspiration"
* #Sputum "Sputum specimen" "Sputum specimen"
* #Isolate "Microbial isolate" "Microbial isolate"
* #Faeces "Faeces specimen" "Faeces specimen"
* #Drain "Swab of building drain" "Swab of building drain"
* #Shower "Swab of building shower" "Swab of building shower"
* #Sink "Swab of building sink" "Swab of building sink"
* #Room "Swab of building room" "Swab of building room"
* #Wound "Specimen from wound" "Specimen from wound"
* #Device "Specimen from device" "Specimen from device"
* #Burn "Burn tissue" "Burn tissue"
* #Abscess "Specimen from abscess" "Specimen from abscess"
* #AbdominalAbscess "Specimen from intra-abdominal abscess" "Specimen from intra-abdominal abscess"
* #AbdomenAbscess "Specimen from intra-abdominal abscess" "Specimen from intra-abdominal abscess"
* #?Collection "Specimen of unknown material" "Specimen of unknown material"
